### PR TITLE
Rename account to app in DripsHub

### PR DESCRIPTION
**Pull request by CodeSandwich**
Closes https://github.com/radicle-dev/drips-contracts/issues/162. CC: @gh0stwheel

The PR also contains some final cleanups of the v0.1 sub-accounts, it was finally easy to catch the last few mentions of them and even an obsolete test.

### CODE REVIEW

**Comment by xmxanuel** [comment]
I think it would be nice to also rename the `AddressId` to `AddressDrips`.

**Comment by CodeSandwich** [comment]
But what about splits? `AddressId` is wide enough to cover the whole protocol, `AddressDrips` suggests that it can be used only for identification of drips.

**Comment by xmxanuel** [comment]
AddressApp is also very good. I just want to increase the probablility if
you want to build on Drips that you open the right contract.

Igor Żuk ***@***.***> schrieb am Mo., 27. Juni 2022, 11:48:

**Comment by CodeSandwich** [comment]
Renamed `AddressId` to `AddressApp`, @xmxanuel

**Review by xmxanuel — APPROVED** [review]

**Pull request merged**
